# Generated by Django 4.2.23 on 2026-05-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periodes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('confirme', 'Confirmé'), ('annule', 'Annulé'), ('present', 'Présent'), ('absent', 'Absent')], default='confirme', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous_set', to='periodes.creneau')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rendezvous',
                'unique_together': {('etudiant', 'creneau')},
            },
        ),
    ]
