# Generated by Django 4.2.23 on 2026-05-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('periodes', '0002_periodevisite_medecin'),
        ('rendezvous', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='est_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='periodes.periodevisite'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
