# Generated by Django 4.2.23 on 2026-05-31 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periodes', '0002_periodevisite_medecin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rendezvous', '0002_rendezvous_est_urgent_rendezvous_periode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('visite_programmee', 'Visite programmée'), ('rappel_rdv', 'Rappel RDV'), ('resultat_disponible', 'Résultat disponible'), ('info', 'Information')], default='info', max_length=30)),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('archivee', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='periodes.periodevisite')),
                ('rendezvous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rendezvous.rendezvous')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
