# Generated by Django 4.2.23 on 2026-05-31 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodeVisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('departement', models.CharField(choices=[('GCA', 'Génie Civil et Architecture'), ('AGEPD', 'Agriculture, Élevage et Produits Dérivés'), ('INFOTEL', 'Informatique et Télécommunications'), ('HYMAE', 'Hydraulique et Maîtrise des Eaux'), ('SCIENV', 'Sciences Environnementales'), ('AHN', 'Art et Humanité Numérique'), ('ESB', 'Enseignement Scientifique de Base'), ('GTC', 'Génie Textile et Cuir'), ('ENREN', 'Énergies Renouvelables'), ('MCHP', 'Météorologie, Climatologie, Hydrologie, Pédologie')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heure_debut', models.TimeField(help_text='Heure de début des consultations')),
                ('heure_fin', models.TimeField(help_text='Heure de fin des consultations')),
                ('capacite_par_creneau', models.PositiveIntegerField(default=4)),
                ('statut', models.CharField(choices=[('programmee', 'Programmée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='programmee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notif_envoyee', models.BooleanField(default=False)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Période de visite',
                'db_table': 'periodes_visite',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='EtudiantImporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('matricule', models.CharField(max_length=50)),
                ('departement', models.CharField(choices=[('GCA', 'Génie Civil et Architecture'), ('AGEPD', 'Agriculture, Élevage et Produits Dérivés'), ('INFOTEL', 'Informatique et Télécommunications'), ('HYMAE', 'Hydraulique et Maîtrise des Eaux'), ('SCIENV', 'Sciences Environnementales'), ('AHN', 'Art et Humanité Numérique'), ('ESB', 'Enseignement Scientifique de Base'), ('GTC', 'Génie Textile et Cuir'), ('ENREN', 'Énergies Renouvelables'), ('MCHP', 'Météorologie, Climatologie, Hydrologie, Pédologie')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiants_importes', to='periodes.periodevisite')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etudiants_importes',
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('capacite', models.PositiveIntegerField(default=4)),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='periodes.periodevisite')),
            ],
            options={
                'db_table': 'creneaux',
                'ordering': ['date', 'heure_debut'],
            },
        ),
    ]
