# Generated by Django 4.2.23 on 2026-05-31 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('periodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodevisite',
            name='medecin',
            field=models.ForeignKey(blank=True, db_column='medecin_id', db_constraint=False, limit_choices_to={'is_active': True, 'role': 'medecin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodes_assignees', to=settings.AUTH_USER_MODEL),
        ),
    ]
